### PR TITLE
enhance front-end

### PR DESCRIPTION
**Pull request by rafapolo**

### CODE REVIEW

**Comment by rafapolo** [comment]
should I change it for the {cert} itself?

**Comment by stef** [comment]
yes, thank you. all my comments are comments that signal what needs to be done for merging.

**Comment by rafapolo** [comment]
Yup. I got back some of the mentioned things... anything else?

**Comment by rafapolo** [comment]
since HTML5 web is much more semantic :) I use extra attributes a lot, it is even recommended in many cases. That is ok to have spaces, since is a string. i could use the ids, but them would have to pass it to template... decided to use the param that we already have there, so.

**Comment by stef** [comment]
hehe :) ok.

**Comment by stef** [comment]
and the css thing is not important?

**Comment by rafapolo** [comment]
the javascript set the style, if there is no js there is no animation - ok as well

**Comment by stef** [comment]
awesome

**Pull request closed without merging**
